### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/.../IST-Net-main/data/Real/test/scene_1/0000_label.pkl'

### ISSUE THREAD

**Issue by Fraplinkin** [CVMI-Lab/IST-Net#3] opened 2023-09-14 08:04 UTC
Thanks for your work! There is an error occurred when I run the test, it just can't find the **xxxx_label.pkl files**, and how can I get them?

**Comment by Eddieeee-Liu** [comment] 2023-09-14 08:36
Sorry could you please show me the structure of the folder "IST-Net-main/data"? I guess you didn't link the original data to the "IST-Net-main/data"

**Comment by Fraplinkin** [comment] 2023-09-15 03:27
![data](https://github.com/CVMI-Lab/IST-Net/assets/63858562/3e0f312b-2491-4d70-ae0e-8fcde332e1ec)
I follow the guidance of DPDN, maybe I made something wrong..

**Comment by Eddieeee-Liu** [comment] 2023-09-15 07:52
Are these folder placed in the path IST-Net-main/data? You can check manually to see if you have the file scene_1/0000_label.pkl in the folder as you have shown above. If the file exist, I think there is sth wrong with the relative path.

**Comment by Fraplinkin** [comment] 2023-09-15 11:49
Hi, Liu, I think I solve this problem and can run the test.
The **.pkl files** are generated from the **data_processing.py** copied from [DPDN,](https://github.com/JiehongLin/Self-DPDN/blob/main/data_processing.py) so I checked the code of **data_processing.py** and found the last line was commented:
`# annotate_test_data(data_dir)` 
But the real test .pkl files should be generated from it, so I uncommented this line and rerun data_processing.py. Then, another error occur:
**FileNotFoundError: [Errno 2] No such file or directory: '/.../IST-Net-main/data/results/nocs_results/real_test/results_test_scene_1_0000.pkl'**
There is no such files in the original NOCS datasets but I found them in [SPD](https://github.com/mentian/object-deformnet). It provides predictions of NOCS from [here](https://drive.google.com/file/d/1p72NdY4Bie_sra9U8zoUNI4fTrQZdbnc/view?usp=sharing). By downloading and putting them in the right path and rerun data processing, I get the files **scene_x/xxxx_label.pkl** needed. 
I run the test successfully and get the same results as in your paper.

**Comment by Eddieeee-Liu** [comment] 2023-09-16 11:59
Nice! Since the problem is solved, I will close this issue!

**Closed as completed by Eddieeee-Liu** 2023-09-16 11:59 UTC
